### ISSUE TITLE
0.1.0 breaks superagent tests

### ISSUE THREAD

**Issue by kornelski** [shouldjs/http#4]
> Right-hand side of 'instanceof' is not an object
> at TypeChecker. (__zuul/test-bundle.js:6779:13)
> at TypeChecker.getFirstMatch (__zuul/test-bundle.js:7347:32)
> at TypeChecker.getType (__zuul/test-bundle.js:7355:22)

To reproduce:

* clone superagent source
* `npm i should-http@0.1`
* `make test-browser-local` and open `http://localhost:4000/__zuul` in a browser

**Comment by btd** [comment]
Thanks. Will take a look.

**Comment by btd** [comment]
Fixed in 0.1.1

**Comment by kornelski** [comment]
Thank you
