### ISSUE TITLE
uncaughtException TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by evaletolab** [shouldjs/http#5]
Hi, 
I got this error after upgrading my node env from v4.2.6 to v6.9.5 `(tested with shouldjs 6.x or 7.x)`. Right now I'm trying to get more details, but maybe you have some ideas.

Exception caused right after,
`var should = require("should");require("should-http");`

```
uncaughtException TypeError: Cannot read property 'type' of undefined
    at module.exports (karibou-api/node_modules/should-http/http-node.js:11:25)
    at Function.should.use (karibou-api/node_modules/should/lib/should.js:143:3)
```

Regards, Olivier

**Comment by btd** [comment]
Can you please provide more details. should.js before 7 used getters for assertions like:
```js
a.should.be.String;
```
since 7.0
```js
a.should.be.String();
```

So it is important to know which exatly vesions you are using.

**Comment by evaletolab** [comment]
I did some test with version 6.x, 7.x, 10.x and 11.0. Version 11.0 is ok but I have to refactor all my tests (as you mention it before). I'm trying to resolve the issue for the version bellow 11.0. 
https://github.com/shouldjs/should.js/compare/10.0.0...11.0.0#diff-4b0c94a9b9f6ecb19127759f32c63aabR48

**Comment by btd** [comment]
I checked what versions of shouldjs 10.x used. It will not be possible to port the same formatting. This means you will not get any benefit from trying to use this module with 10.x.

**Comment by btd** [comment]
Could you please explain what is breaking for you in shouldjs 11.x? I will try in future do less such brecking releases.

**Comment by evaletolab** [comment]
Sorry I was not clear, 
I have to keep my version of should to 6.x (and also should-http to 0.0.1) until I did all refactoring of getters assertions `a.should.be.<name>()` 
Cheers, Olivier

**Comment by btd** [comment]
Sorry, there is no easy fix for this (i originally when did migration, did this with sed), but result worth it - for me there were at least 2 places where false positive assertion happen.

**Comment by evaletolab** [comment]
I will use grep "should\.be\." to get the list and replace all one by one !
Is there a way to contraint should-http version to 0.0.1 when using should <7.0 ?

**Comment by btd** [comment]
@evaletolab if you specify exact version in package json it will be used. should-http 0.0.1 did not have any dependencies, so you will not have any problems with this.

**Comment by evaletolab** [comment]
It's exactly what I did!  1000 thanks @btd!
